apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt2play.fullname" . }}
  labels:
    {{- include "mqtt2play.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mqtt2play.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mqtt2play.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.config }}
          env:
          {{- range $k, $v := . }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
          {{- end }}            
          volumeMounts:
          - mountPath: /dev/snd
            name: snd
          {{- if .Values.persistence.enabled }}              
          - mountPath: /opt/mqtt2play/sfx
            name: sfx
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: snd
        hostPath:
          path: {{.Values.sndPath | default "/dev/snd"}}
          type: ""
{{- if .Values.persistence.enabled }}          
      - name: sfx
        persistentVolumeClaim:
          claimName: {{ include "mqtt2play.fullname" . }}-sfx
{{- end }}