{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mqtt2play.fullname" . }}-sfx
  labels:
    {{- include "mqtt2play.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.persistence.size }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{.}}
  {{- end }}
  volumeMode: Filesystem
  volumeName: pvc-a9539b16-c10c-48d4-90e5-c91ecf403493
  {{- end}}